networks:
  openfirenet:
    driver: bridge

services:
  openfire:
    build: 
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
     - TZ=${TZ}
    container_name: ${JABBER_HOST}-openfire
    hostname: ${JABBER_HOST}
    volumes:
      - ./data/attachments/${JABBER_HOST}:/usr/share/openfire/data/attachments/${JABBER_HOST}
      - ./data/certbot:/etc/letsencrypt
    ports:
      - "5222:5222"
      - "5223:5223"
      - "7070:7070"
      - "7443:7443"
      - "5269:5269"
      - "5270:5270"
      - "5275:5275"
      - "5276:5276"
      - "9090:9090"
      - "9091:9091"
      - "7777:7777"
      - "10005:10005/udp"
      - "10015:10015/udp"
    restart: always
    depends_on:
      - database
    networks:
      - openfirenet

  database:
    image: postgres:16-alpine
    volumes:
      - ./data/database/:/var/lib/postgresql/data
    env_file: .env
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_ROOT_PASSWORD: $DB_ROOT_PASSWORD
    ports:
      - "5434:5432"
    tty: true
    restart: always
    networks:
      - openfirenet

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot:/etc/letsencrypt
    environment:
      EMAIL: $EMAIL
      PREFERRED_CHALLENGES: dns
      DOMAINS: "search.$JABBER_HOST conference.$JABBER_HOST xmpp-client.$JABBER_HOST xmpp-server.$JABBER_HOST"
      RSA_KEY_SIZE: 4096
    command: certonly 
